spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://47.109.206.82/book_nine?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/static/'
    suffix: '.html'
    servlet:
      content-type: 'text/html '
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100000000
  transaction:
    rollback-on-commit-failure: true
    dafult-timeout: 30
  mvc:
    converters:
      preferred-json-mapper: jackson

# 正确的格式
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.book.book.model.pojo
  mapper-locations: classpath:mapper/*.xml

  server:
    port:8080

